service: monorepo-test
app: monorepo-test
org: jschuur

frameworkVersion: '3'

plugins:
  - serverless-plugin-monorepo
  - serverless-webpack
  - serverless-webpack-prisma

custom:
  webpack:
    includeModules: true
    # packager: pnpm
    # packagerOptions:
    #   noFrozenLockFile: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: src/hello.handler
    events:
      - httpApi:
          method: get
          path: /hello
  animals:
    handler: src/animals.handler
    events:
      - httpApi:
          method: get
          path: /animals
